### ISSUE TITLE
meaning of "Digest required to delete manifest"?

### ISSUE THREAD

**Issue by mdagit** [regclient/regclient#106]
If I do:
`$ regctl image delete localhost:5000/my-apps:master-2021-10-21`
I get:
`Digest required to delete manifest, reference localhost:5000/my-apps:master-2021-10-21`
but i don't know what this really means, nor why it would be true. 
Doesn't image delete using tag get rid of both the tag reference as well as the underlying blobs?

**Comment by sudo-bmitch** [comment]
I think the `docker image rm` example was another that gave me hesitation since that's just doing an untag:

```
$ docker image tag registry:2.4.1 registry:copy

$ docker image ls registry
REPOSITORY   TAG           IMAGE ID       CREATED         SIZE
...
registry     2.4.1         8ff6a4aae657   5 years ago     172MB
registry     copy          8ff6a4aae657   5 years ago     172MB

$ docker image rm --force registry:copy
Untagged: registry:copy

$ docker image ls registry
REPOSITORY   TAG           IMAGE ID       CREATED         SIZE
...
registry     2.4.1         8ff6a4aae657   5 years ago     172MB
```

I recall using the `docker image rm --force` to untag an image when there was currently a container created with that image, but even then the underlying image wasn't deleted since the container existed.

I've gone ahead and added the option anyway, but left a "this is unsafe" note on the flag. If people experience unexpected data loss with the flag, I'm not sure what else could have been done to direct them to other options.
