### ISSUE TITLE
[Issue] regctl from Docker image does not show repos

### ISSUE THREAD

**Issue by jeffrson** [regclient/regclient#120]
### Current Behavior

I'm calling regctl from Docker image as follows:

```
docker container run -it --rm --net host \
-v /home/user/.regctl:/home/appuser/.regctl/ \
-v /etc/docker/certs.d:/etc/docker/certs.d:ro regclient/regctl repo ls
```

However, this results in an error message:
`accepts 1 arg(s), received 0`

### Expected Behavior

List repositories, like
`curl -i -k https://<registry>:5000/v2/_catalog`

of course I had set the registry with `regctl repo set --hostname` - which indeed works since the command first complained about the unknown certificate.

Edit:
It works, however, when I append hostname:port. But IMO this should not be necessary. Furthermore, "tag ls <repo>" does not find repo, although the repo is list via curl and with appended hostname:port. Maybe this is related?

Edit2: it complains, for instance, about not finding the repo via "library":
 {"errors":[{"code":"NAME_UNKNOWN","message":"repository name not known to registry","detail":{"name":"library/nginx"}}]}
That's strange, since `curl <registry>/v2/nginx/tags/list` works fine - is there any incompatibility?

### Version

```text
"Labels": {
                "maintainer": "",
                "org.opencontainers.image.authors": "Regclient contributors",
                "org.opencontainers.image.created": "2021-10-04T00:37:10Z",
                "org.opencontainers.image.description": "",
                "org.opencontainers.image.documentation": "https://github.com/regclient/regclient",
                "org.opencontainers.image.licenses": "Apache 2.0",
                "org.opencontainers.image.revision": "0cb9b4c8bc5394be47432b3c884ff7933d40d0b8",
                "org.opencontainers.image.source": "git://github.com/regclient/regclient.git",
                "org.opencontainers.image.title": "regctl",
                "org.opencontainers.image.url": "https://github.com/regclient/regclient",
                "org.opencontainers.image.vendor": "",
                "org.opencontainers.image.version": "v0.3.9"
            }

```

### Environment

- Running as binary or container: container
- Host platform: linux
- Registry description:  registry:2

**Comment by sudo-bmitch** [comment]
I'm worried you may have modified the configuration for Docker Hub rather than configuring the settings for your local registry. You can view the config with `regctl registry config` or just view the `/home/user/.regctl/config.json` file. If you've misconfigured it, you can always delete that file to start over, but the `docker.io` entry should normally be set to:

```json
  "docker.io": {
    "tls": "enabled",
    "hostname": "registry-1.docker.io"
  }, 
```

You would then run commands like `regctl registry set registry.example.com:5000` and `regctl registry login registry.example.com:5000` to configure your login on `registry.example.com:5000`, which would be used by other regctl commands.

The rest of the confusion seems to be related to associating one command to the previous command. Like curl needs the url for each command, regctl needs the registry/repo/image name for each request. The only exceptions are the `regctl registry` commands that save the configuration to the config.json file to avoid needing to specify how to access your registry on every command.

So if you only ask it for `regctl tag ls nginx` it will expand that image name to `docker.io/library/nginx:latest`, same way the docker commands do. Instead, you need to run `regctl tag ls registry.example.com:5000/nginx` to list your local registry.

**Comment by jeffrson** [comment]
Thank you for this detailed explanation!

Yes - apparently I had overwritten "docker.io"'s hostname. Now I have
```
{
  "hosts": {
    "registry.example.com:5000": {
      "tls": "enabled",
      "hostname": "registry.example.com:5000"
    }
  }
}
```

So I always have to specify this "identifier" (first element following "hosts")?

Because I strongly believe I already had tried this with tag (but before setting the registry). Now it works.

Great! Thank you!

**Comment by sudo-bmitch** [comment]
Yes, the commands need the full image reference (registry/repository/tag) or it defaults back to Docker Hub.

I'm probably overdue to update that demo, but there's also some other stuff in the works I'd like to finish first, and then have more in the demo. I'll look at using other registry names there when I do that. Thanks for the feedback!
