### ISSUE TITLE
[Issue] --platform argument not work in regctl image inspect command

### ISSUE THREAD

**Issue by Huweicai** [regclient/regclient#128]
![图片](https://user-images.githubusercontent.com/29170746/147473754-474f9d83-114d-43fd-ac26-13fe818da15f.png)

I am run regclient on mac to get linux image info from dockerhub, but `regctl image inspect` do not work as expected:
```
- regctl manifest get --platform linux/amd64 alpine ✅
- regctl image inspect --platform linux/amd64 alpine ❌
```

**Comment by sudo-bmitch** [comment]
Thanks for the report. I believe this got fixed in #123. I need to tag and release these commits, so if that looks right in some testing, I'll get that released shortly. While waiting for that, the edge release of the container images and binaries in the [GHA artifacts](https://github.com/regclient/regclient/actions/runs/1609168346) would contain this fix too.

**Comment by sudo-bmitch** [comment]
@Huweicai  The v0.3.10 release just went out. Have a look and let me know if that solves your issue. Thanks!

**Comment by Huweicai** [comment]
Yes, it works, thank you for solving so fast.
