### ISSUE TITLE
Is there a way to set custom User-Agent header?

### ISSUE THREAD

**Issue by Noksa** [regclient/regclient#145]
I'm trying to copy images from docker.io to my private docker registry and it sits behind nginx reverse-proxy.
So I check `User-Agent` header and if it is docker/containerd/etc - a request goes to docker registry.

Can I set custom User-Agent somehow in `image copy` command?

**Comment by sudo-bmitch** [comment]
It's set as a constant right now. Perhaps that could be a configuration option. However if you have control of your reverse proxy, you may find it easier to filter based on requests going to `/v2/*` since all registry requests from any OCI client should be under that path. That would help not only with regclient, but any other runtimes you may use, and registry tooling.
