### ISSUE TITLE
[Feature] option to only sync n most recent tags for an image

### ISSUE THREAD

**Issue by thinkmassive** [regclient/regclient#215]
First off, this is an excellent tool! It's been very helpful for me over the past few months, and I'm grateful you created it.

### Current Behavior

I have some images with unique daily tags, which cause me to hit Dockerhub rate limits increasingly often. Some images also have a rolling daily tag, but the unique tags are often preferable to see exactly what's running in a deployment at a glance.

My short term workaround is using dedicated credentials for each of these images, and decreasing the frequency of these jobs over time. Obviously the cycles will continue to increase, and soon they'll be longer than 24 hours, so I'm looking for a more durable solution.

### Example Solution

Based on #198 it seems straightforward to sort the tag list by date, so I'm wondering if it would be feasible to add an optional parameter like `recentTagLimit` that would only attempt to compare (and sync if needed) that number of tags, starting with the most recent. This seems like it would avoid a lot of unnecessary requests that end up comparing the ever-growing list of already-synced tags.

If there's an existing solution that others are using to address this issue I'm glad to use it instead of extending the tool itself. The only alternative I've come up with is regularly updating the tag regex, but I would much rather set those once and forget them if possible.

---

This is purely a feature request, nothing is functioning in an unexpected way. I removed headings that seemed intended for bug reports, but please let me know if you want additional info that will help triage this suggestion. Thank you!

**Comment by sudo-bmitch** [comment]
Hi @thinkmassive, I'm curious what your current sync steps look like today. E.g. are you using the `platform` or `ratelimit` options? If you can post an example, there may be other ways to get a lot more out of your current sync cycles.

Adding a limit to the number of images synced per scheduled action would be easy, but the hard part will be sorting in a way that will make everyone happy. Sorting by string works in some cases, like  date stamps in ISO 8601, won't work for semver or code names (like the debian releases use). And the sort order will vary by use case too.

It quickly gets into the use case regbot was designed to handle. With the current Lua libraries, that wouldn't be pretty, but it would work. I'd like to make requests like this a lot easier to do over there with both convenience functions to simplify the needed scripting and a lot more examples since few of us spend much time in Lua.

**Comment by thinkmassive** [comment]
Hi @sudo-bmitch, I use a few Jobs, each running a one-shot `regsync`. They are split because some images use different credentials, so I have one "general" job and a few single-image jobs.

For each job I use a default `ratelimit` with `min: 10` and `retry: 15m` (tuned these once during initial setup, maybe I should increase the `retry` delay). For each image I specify a single `platform`, and a `tags.allow` regex.

I haven't dug into the code here, so it's possible I'm misinterpreting what I think I'm seeing in logs... It looks like `regsync` initially requests the tags list from the source registry, then requests the manifest for every tag.

It seems like we could request the source and destination tag lists, then only fetch manifests for tags that either:
1. are missing from the destination
2. have a different digest

(now that I write this out, I feel like this might be a better feature than time-sorting, or I'm misunderstanding the `regsync` sequence of events)

When I request `https://hub.docker.com/v2/repositories/<owner>/<image>/tags` I also see `tag_last_pushed`, which is why I thought sorting by most recent would be another option. I realize the result from that request could be different than from `registry-1.docker.io/v2/<owner>/<image>/tags` but I used the former because it was easy using [this kb article](https://hub.docker.com/support/doc/how-do-i-authenticate-with-the-v2-api).

**Comment by sudo-bmitch** [comment]
@thinkmassive 
> I haven't dug into the code here, so it's possible I'm misinterpreting what I think I'm seeing in logs... It looks like `regsync` initially requests the tags list from the source registry, then requests the manifest for every tag.
> 
> It seems like we could request the source and destination tag lists, then only fetch manifests for tags that either:
> 
>     1. are missing from the destination
>     2. have a different digest
> 
> (now that I write this out, I feel like this might be a better feature than time-sorting, or I'm misunderstanding the `regsync` sequence of events)

That's the behavior of regsync today unless an option like force recursive or specifying a platform done which is why I was curious to see an example of your sync config. The code for that is:

https://github.com/regclient/regclient/blob/13ca7c263aa3613015b953874bdb30589347afa2/cmd/regsync/root.go#L569-L591

regclient is using head requests for checking the rate limit and tag digests, so we should only be pulling manifests in a handful of cases, one of them being an image that needs to be copied.

> When I request `https://hub.docker.com/v2/repositories/<owner>/<image>/tags` I also see `tag_last_pushed`, which is why I thought sorting by most recent would be another option. I realize the result from that request could be different than from `registry-1.docker.io/v2/<owner>/<image>/tags` but I used the former because it was easy using [this kb article](https://hub.docker.com/support/doc/how-do-i-authenticate-with-the-v2-api).

Unfortunately that Hub API is Hub specific and regclient is just hitting the generic registry API for portability. I've looked at supporting the Hub API, but the parallel authentication and different host for requests, along with different APIs being available based on whether you have a paid account, makes supporting it complicated. I'd love to get a bunch of this added metadata into the OCI spec for tag listings, but that will be a long while until it happens.

**Comment by thinkmassive** [comment]
> regclient is using head requests for checking the rate limit and tag digests

This is great, I was unfamiliar with HEAD requests and didn't realize they [don't count toward the limit](https://docs.docker.com/docker-hub/download-rate-limit/#definition-of-limits). I suspect when I'm hitting limits it's more likely due to inadvertently changing source tags (occasionally happens since Dockerhub lacks an "immutable" setting) or from not allowing the limits to replenish sufficiently between batches.

> Unfortunately that Hub API is Hub specific

Gotcha, sounds like a ton of work for an open source project! I've been pulling from Dockerhub only because that was the original location for some of my images, but I'm already in the process of making that a mirror instead of the source.

Thanks for the detailed responses. I'll revisit `ratelimit` tuning, and will eventually dig into your codebase more to see if I can contribute back.

**Comment by sudo-bmitch** [comment]
@thinkmassive 
> I suspect when I'm hitting limits it's more likely due to inadvertently changing source tags (occasionally happens since Dockerhub lacks an "immutable" setting) or from not allowing the limits to replenish sufficiently between batches.

Another thing to look at is multi platform images. It's a good practice to pull them all (registries usually reject a partial multi platform list, and digest compares don't work if you compare one platform to a platform list), but each platform is a separate manifest pull that can add up. 

> Edit: a quick reference for getting Dockerhub token and making requests [to the registry API](https://docs.docker.com/docker-hub/download-rate-limit/#how-can-i-check-my-current-rate) (instead of Hub API) is also on the rate limit page

That rate limit check is hitting the registry API instead of the Hub API. Regclient is pulling that same token. But the token for the Hub API was different last time I looked. I think they were using a JWT.
