### ISSUE TITLE
[Feature] Print "location" header returned by registry

### ISSUE THREAD

**Issue by nishakm** [regclient/regclient#241]
### Current Behavior

Pushing a blob successfully does not provide a digest
```
$ regctl artifact put -f sbom 127.0.0.1:8080/remote/sbom
```

### Expected Behavior

It would be nice to print the "location" header  returned by the registry

```
$ regctl artifact put -f sbom 127.0.0.1:8080/remote/sbom
Location:[/v2/remote/sbom/manifests/sha256:49970eca2733b6ed27c5ea8590caf13d0e11220afcf4f1458b86d74573bac4b4]
```

### Version

```text
04956605e6a2526f601c169e727ca88421c24b2d
```

**Comment by sudo-bmitch** [comment]
I don't have a good path in the code to take the http headers and pass them back up since the ManifestPut is only returning an error right now. And this wouldn't be helpful with other schemes like ocidir.

But I think the `--by-digest` argument added in #242 may get the result you're looking for. When pushing by digest, instead of assuming the `latest` tag, it computes the digest on the manifest before pushing, pushes to that digest, and returns the digest in the output. And since the digest is computed on the client side, that will also work with other schemes.

Let me know if that gets you the desired result.

**Comment by nishakm** [comment]
That worked for me. Thanks! I'll close this.
