### ISSUE TITLE
[Question] support registry behind a proxy?

### ISSUE THREAD

**Issue by shaofeng66** [regclient/regclient#360]
Didn't see proxy settings in help nor related code in confi.Host{}, is there any plan to support?

### Version

```text
(paste output of `regctl version` or similar for binaries, or `docker image inspect regclient/...` on the image and paste the labels)
{
  "VCSRef": "732c2a3a6312fc70dfcfcd821505ef0ad1ed230f",
  "VCSTag": "v0.4.5"
}
```

### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment]
Hi @shaofeng66. I'm not clear from the question if this is a reverse proxy like nginx and traefik, or if your outbound network access must go through a proxy. For a reverse proxy, you would connect to the DNS name where the proxy serves the registry. For an outbound proxy, you would define the `HTTP_PROXY` and `HTTPS_PROXY` variables, similar to using curl and other networking tools.

If this isn't helpful, please show the steps you use to connect to the registry with a command like `curl https://registry.example.com/v2/` and the output of connecting with regctl.

**Comment by shaofeng66** [comment]
Thanks for you reply.
I am integrating regclient as a library in my go program to copy image from one registry to another, the outbound network access to some registries must go through a proxy. It looks like HTTP(S)_PROXY is globally, is it possible to set proxy only for subset of the hosts?

**Comment by sudo-bmitch** [comment]
You would typically use the `NO_PROXY` variable for items you don't want to proxy. Since you are writing the code yourself, you can define multiple `http.Client` values, with separate proxies, and have a separate regclient instance for each, but you won't be able to easily copy between registries in that scenario.

Also if what you're asking about isn't a proxy but rather a mirror, there is a Hostname and Mirror value in the config. Hostname is useful when you reference a registry with a different DNS name than what is typed in the image reference, e.g. `registry-1.docker.io` instead of `docker.io`. Mirror is useful to define one or more alternate sources of read only content for an upstream registry.
