### ISSUE TITLE
Login config file generated is different when used with flags

### ISSUE THREAD

**Issue by pshanoop** [regclient/regclient#38]
`regctl registry login registry.private -u user -p password`
This generates config file `~/.regctl/config.json`
```json
{
  "hosts": {
    "registry.private": {
      "user": "user",
      "pass": "private"
    }
  }
}
```
and all request fails with unauthorized error but same time 
`regctl registry login registry.private` then enter username and password. This generates 
```json 
{
  "hosts": {
    "registry.private": {
      "scheme": "https",
      "tls": "enabled",
      "dns": [
        "registry.private"
      ],
      "user": "user",
      "pass": "password"
    }
  }
}
```
and then this works.

**Comment by sudo-bmitch** [comment]
Thanks for the report. I believe this is a case of the shell parsing special characters in the password string rather than a different behavior in `regctl` itself. All of the additional fields are default values that would get automatically set when reading an existing config vs creating a new config, so any command that updates the config may add those fields.

I'm working through a refactor that will change how this config is handled, and in that branch, I'm not seeing authorization issues with the config.json in the first state, so if there are issues with this, it will be fixed in the next release.

**Comment by sudo-bmitch** [comment]
With the latest release, this should be fixed, or at least look different. If you're still having issues, let me know and we can reopen this.
