### ISSUE TITLE
[Request] Provide official sha256sum for releases

### ISSUE THREAD

**Issue by yeikel** [regclient/regclient#402]
We consume the releases published at https://github.com/regclient/regclient/releases/  such as https://github.com/regclient/regclient/releases/download/v0.4.7/regsync-windows-amd64.exe

Currently, there is no way to validate the integrity of the downloads as there is no checksum information attached to the release. We can calculate and store the checksum for subsequent integrity checks of the downloads, but that does not help with the initial validation as we can only use the provided binary as the source of truth

Ideally, each published artifact should attach a `.sha256`  file with the calculated hash of the release

Would it be possible to consider this? 

Read more : https://www.apache.org/info/verification.html

**Comment by sudo-bmitch** [comment]
Hi @yeikel. Since checksums only verify the file has not been tampered in transit, and https also provides that guarantee, they aren't provided for this project. Notably since checksums and the artifacts are stored in the same location, an attacker changing the artifact could also change the checksum.

Instead, regclient uses signing of the binaries and images using cosign to verify the artifact was generated by the GitHub Action build. Details on how to verify those signatures are included in the installation docs: https://github.com/regclient/regclient/blob/main/docs/install.md

**Comment by thesayyn** [comment]
Just my two cents, checksum file still provides value if you are fetching regclient through an Artifactory, using tools such as Bazel.

**Comment by sudo-bmitch** [comment]
> Just my two cents, checksum file still provides value if you are fetching regclient through an Artifactory, using tools such as Bazel.

What is the checksum doing in that scenario? My hesitation is to avoid a false sense of security.

**Comment by thesayyn** [comment]
Under bazel, it used for caching, and immutability guarantee when the artifact is fetched through an read-through proxy. It does what the sigstore does but more primitive.

**Comment by sudo-bmitch** [comment]
> Under bazel, it used for caching, and immutability guarantee when the artifact is fetched through an read-through proxy. It does what the sigstore does but more primitive.

For caching, you want to use the [ETag HTTP header](https://en.wikipedia.org/wiki/HTTP_ETag).

Using the sha256 would tell you proxy didn't modify the content, but only if you pulled the sha256sum without using the proxy. And it doesn't guarantee that the original registry didn't modify the content, which is why signing is preferred. Attacks like the xz vulnerability would be more difficult to hide if artifact consumers verified the signature was from GitHub Actions on public commits.

**Comment by thesayyn** [comment]
> For caching, you want to use the [ETag HTTP header](https://en.wikipedia.org/wiki/HTTP_ETag).

Oh i mean on the client side, some build tools cache artfiacts from internet by their content checksum. 

> And it doesn't guarantee that the original registry didn't modify the content, which is why signing is preferred. Attacks like the xz vulnerability would be more difficult to hide if artifact consumers verified the signature was from GitHub Actions on public commits.

No arguments here, i agree.
