### ISSUE TITLE
[Feature] Limit sync images to specific timeframe

### ISSUE THREAD

**Issue by runningman84** [regclient/regclient#521]
### Current Behavior

The sync process does not take into account when something changed. 

### Expected Behavior

It would be cool to have a filter option like max age: 30 days. This would allow us to sync big repos from docker hub without syncing the history of the last x years.

Filtering them using tags is not very easy because each repo has it's own naming concept...

### Example Solution

New paramater:
max-sage: 30days

**Comment by sudo-bmitch** [comment]
This is going to be challenging to implement in a generic way that won't be broken by a lot of different scenarios. The tag listing in OCI does not include when the tag was created or last pushed. The two options I can think of are the created time inside the image config and the OCI annotation for the created time in the manifest.

The gotchas to the image config include:

- There are technically two types of image configs (OCI and Docker) but we can parse the Docker config with the OCI syntax (since they are compatible).
- Artifacts pushed to an OCI registry use a different config, so they can't be parsed generically, assuming they set a value somewhere.
- The created time in the image config can be faked. Various reproducible builders will either backdate this or exclude it entirely.
- Multi-platform images will have a different image config for each platform.
- Getting to this value requires pulling the manifest and then pulling the image config. You'd save time on the layer copy, but there will be significant overhead per tag being checked, so you don't want to run it in a frequent loop.

For the annotation, you still need to pull the manifest, it only exists on OCI manifests (Docker manifests don't technically have annotations), and it's rarely included on container images because of a lack of build tooling support for annotations.

Possibly the best option is to script something either in shell with regctl or with regbot. But you'd want to decide how to handle the various complications if you encounter them.

**Comment by runningman84** [comment]
In our old solution we just queried the docker hub api which hast a last updated attribute for all images. The solution worked fine but did just copy everything even if the image was already at the destination. This caused pull limit errors…

**Comment by sudo-bmitch** [comment]
Unfortunately the Docker Hub API is specific to Hub and won't work for other registries. There's a desire to extend the tag listing API in OCI, but that's a long way off, and adoption of OCI changes takes time.

There are a few features in regclient that will help. regsync lets you check the current rate limit and pause when a threshold is reached. And when run as a server, it will make the first pass on tags that don't exist on the destination.
