### ISSUE TITLE
[Feature] Regsync - Enable support of referencing configuration file from git

### ISSUE THREAD

**Issue by fdolsky321** [regclient/regclient#567]
### Current Behavior

Configuration file is supported only from filesystem.

### Expected Behavior

 As I wanna deploy regsync to kubernetes, I wanna create single `Deployment` which will just specify in its config the git url of the configuration file for regsync.

### Example Solution

```bash
export HUB_USER=your_username
mkdir -p ${HOME}/.docker
echo "your_hub_password" >${HOME}/.docker/hub_token
docker container run -i --rm --net registry \
  -v "$(pwd)/regsync.yml:/home/appuser/regsync.yml:ro" \
  -v "${HOME}/.docker/hub_token:/home/appuser/.docker/hub_token:ro" \
  -e "HUB_USER" \
  ghcr.io/regclient/regsync:latest -c git@github.com:regclient/regclient.git/docs/examples/regsync.ymlserver
```

### Version

```text
0.5.2
```

### Environment

- Platform: Linux
- Your registry: Docker Hub, JFrog Artifactory

- Running as container:
- Host platform: kubernetes
- Registry description: Syncing from dockerhub to internal Artifactory

**Comment by sudo-bmitch** [comment]
I've been thinking about this one for a bit, and one thought I keep coming back to is whether storing the config in a registry as an artifact, or via HTTP, would work for your use case? That would avoid the need to pull in git libraries, along with needing ssh keys. Since many git repos have an HTTP(s) URL to pull raw content, it should be possible to get it the content without using the git interface itself.

**Comment by fdolsky321** [comment]
Thanks @sudo-bmitch . I will try this approach and provide feedback whether I will be successful :). Lets keep this with low priority :)
