### ISSUE TITLE
[Question] Is it possible to sync to a Docker daemon? 

### ISSUE THREAD

**Issue by philipcristiano** [regclient/regclient#568]
### Question

Is it possible to target a Docker daemon for regsync/regbot? The config file for syncing across registries is useful and I would love to also pre-fetch images from repositories to a local daemon to avoid pull delays and increase fault tolerance.

### Environment

- Running as binary or container: container
- Host platform: NixOS / Nomad / Docker
- Registry description: registry:2

**Comment by sudo-bmitch** [comment]
The docker engine, and other container runtimes, isn't currently a possible reference. However, you can export/import from both docker and regclient, and an export from one can be imported to the other. For docker, that needs to be done for a single platform with a standard docker install today because it dereferences all images it pulls. I believe the containerd changes that docker is implementing will allow an OCI Layout to be used directly and will support multiplatform images in those imports/exports.

**Comment by philipcristiano** [comment]
Gotcha, thanks! 

The export/import doesn't quite work for my case where I'd like it to be automatic, essentially things regbot/sync does, but I guess against the Docker Engine[ Image Create](https://docs.docker.com/engine/api/v1.43/#tag/Image/operation/ImageCreate) API instead of a registry.

**Comment by sudo-bmitch** [comment]
You may want to have a look at watchtower for that
https://github.com/containrrr/watchtower

**Comment by philipcristiano** [comment]
That seems close but seems to focus on cases where the container is already running/configured on the host and updating the image. I have a [separate-project PoC](https://github.com/philipcristiano/docker-prefetch-image/) testing out the idea.
