### ISSUE TITLE
[Feature] artifacts referring to subjects in different repositories

### ISSUE THREAD

**Issue by Silvanoc** [regclient/regclient#586]
### Current Behavior

`regctl artifact put --subject <subject-ref> <artifact-ref>` fails with `reference and subject must be in the same repository` if `artifact-ref` and `subject-ref` are on different repositories, but in the same registry

### Expected Behavior

`artifact-ref` and `subject-ref` on the same registry are accepted, no matter if they are on different repositories or not.

### Steps To Reproduce

Following script:
```
#!/usr/bin/env bash

set -eu

cleanup() {
    docker rm -f test-subject
}

trap cleanup EXIT

docker run -d -p 5123:5000 --name test-subject ghcr.io/project-zot/zot-linux-arm64:latest
sleep 3

regctl registry set --tls disabled

dd if=/dev/urandom of=./artifact.file bs=1M count=10

skopeo copy --override-os linux --dest-tls-verify=false docker://docker.io/library/alpine:3.18.4 docker://localhost:5123/alpine:3.18.4

echo
echo "🤨 does putting an artifact work?"
regctl artifact put --file ./artifact.file localhost:5123/alpine:v1
echo "✅ Putting an artifact works"

echo
echo "🤨 does putting an artifact with a subject in the same repository work?"
regctl artifact put --subject localhost:5123/alpine:3.18.4 --file ./artifact.file localhost:5123/alpine:v2
echo "✅ Putting an artifact with a subject in the same repository works"

echo
echo "🤨 does putting an artifact with a subject in a different repository work?"
regctl artifact put --subject localhost:5123/alpine:3.18.4 --file ./artifact.file localhost:5123/the-subject-repo:v1
echo "✅ Putting an artifact with a subject in a different repository works"
```

### Version

```text
VCSTag:     v0.5.3
VCSRef:     63bcd1a551acbb357d6a6aea0c50fb193aa77da9
VCSCommit:  63bcd1a551acbb357d6a6aea0c50fb193aa77da9
VCSState:   clean
VCSDate:    2023-10-06T20:40:08Z
Platform:   darwin/arm64
GoVer:      go1.21.1
GoCompiler: gc
```

### Environment

- Running as binary or container: as binary
- Host platform: MacOS
- Registry description: Zot

**Comment by Silvanoc** [comment]
This is the output my script gets in my system:
```
93bb8502af8a7248a29073a1ef15842f6b7e8fbf1e68c45793a605f2442ca062
10+0 records in
10+0 records out
10485760 bytes transferred in 0.014057 secs (745945792 bytes/sec)
Getting image source signatures
Copying blob 579b34f0a95b done
Copying config 3cc2033214 done
Writing manifest to image destination
Writing manifest to image destination
Copying config 71e7d2aec7 done
Writing manifest to image destination

🤨 does putting an artifact work?
WARN[0000] using default value for artifact-type is not recommended
WARN[0000] Changing TLS settings for registry            host=docker.io new=disabled orig=enabled
✅ Putting an artifact works

🤨 does putting an artifact with a subject in the same repository work?
WARN[0000] using default value for artifact-type is not recommended
WARN[0000] Changing TLS settings for registry            host=docker.io new=disabled orig=enabled
✅ Putting an artifact with a subject in the same repository works

🤨 does putting an artifact with a subject in a different repository work?
reference and subject must be in the same repository
test-subject
  /private/tm/test-subject ❯ cat run-test.bash|pbcopy
  /private/tm/test-subject ❯ ./run-test.bash
2305d95df86d4c75f67a6058631d4f939924ca19f4627c6306e6577206c7349a
10+0 records in
10+0 records out
10485760 bytes transferred in 0.013827 secs (758353945 bytes/sec)
Getting image source signatures
Copying blob 579b34f0a95b done
Copying config 3cc2033214 done
Writing manifest to image destination
Writing manifest to image destination
Copying config 71e7d2aec7 done
Writing manifest to image destination

🤨 does putting an artifact work?
WARN[0000] using default value for artifact-type is not recommended
WARN[0000] Changing TLS settings for registry            host=docker.io new=disabled orig=enabled
✅ Putting an artifact works

🤨 does putting an artifact with a subject in the same repository work?
WARN[0000] using default value for artifact-type is not recommended
WARN[0000] Changing TLS settings for registry            host=docker.io new=disabled orig=enabled
✅ Putting an artifact with a subject in the same repository works

🤨 does putting an artifact with a subject in a different repository work?
reference and subject must be in the same repository
```

Notice the last line.

**Comment by sudo-bmitch** [comment]
This is currently part of the design of the OCI referrers API. It doesn't let you query referrers to an image that exist in other repositories. There are several use cases where dangling referrers are desired, though you would need to know the repository to search for that metadata since the registry won't know it. I believe cosign is working to support that model. It isn't explicitly supported in the spec, so registries can refuse to return results until the image is pushed. This part of the spec is under a lot of debate right now, and it's not clear what the resulting GA release will look like. See [distribution-spec #459](https://github.com/opencontainers/distribution-spec/issues/459) for more details on that.

For now I'll consider this a feature request pending the outcome of the upstream OCI specs.

**Comment by Silvanoc** [comment]
I didn't get the expectation of cross-repository references out of the blue, but from the [OCI blog](https://opencontainers.org/posts/blog/2023-07-07-summary-of-upcoming-changes-in-oci-image-and-distribution-specs-v-1-1/#2-new-manifest-field-for-establishing-relationships). The first sentence of the linked section ends with "subject [...] points to another object in the registry". It clearly says "in the registry" and not "in the repository". But since you're involved in the spec discussions, you know better than me and that sentence in the blog is probably simply not clear enough.

I've been looking for a while for more clarity in the spec, to no avail. My feeling is that the "subject" has only the use-case to "attach" artifacts (SBOMs, signatures,...) to a container image and not the other way around (attach a container image to a Docker Compose configuration or to a Helm chart). In that logic, the usage of the container image repository makes sense and therefore no need for a cross-repo reference can be seen. But that's IMO a bit short-sighted on the expectation of using OCI registries for generic artifacts.

BTW after very carefully reading the [OCI referrers API](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) once again, I think I found the sentence limiting "subject" to the same repository (highlighing is mine):

> Each descriptor is of an image manifest **IN THE SAME \<name> NAMESPACE** with a subject field that specifies the value of \<digest>.

Anyway, I agree with you that this is then not a bug, but a feature request.

**Comment by sudo-bmitch** [comment]
The requirement to scope the API to the repository is similar to how references between the Index, Image manifest, and Config/Layer blobs are all scoped to the same repository. Servers and clients always treat those descriptors as references in the same repository namespace. The referrers response is also an Index which contains descriptors to manifests in the same repository, without any reference to a different repository name. A key reason for the namespace scoping is in how authorization is handled in registries. The token server doesn't know all the content, but needs to return access to specific repositories, and the registry cannot give a list of those repositories for a client to request access without exposing potentially private data to that client (registries don't want to give out a list of private repositories (other customers) to other users on the same registry).

> My feeling is that the "subject" has only the use-case to "attach" artifacts (SBOMs, signatures,...) to a container image and not the other way around (attach a container image to a Docker Compose configuration or to a Helm chart). 

Both of these are challenging examples, since it's possible to change the underlying image reference with a variable upon execution. However, if you wanted to package an entire application like this, I'd look to using an Index of images plus a single compose/helm artifact. No need for a subject/referrer, and it is more easily to copy with existing tools. It does mean all the referenced images must be in the same repository, but for authorization, that's a good thing (anyone that can pull the package definition can also pull all the referenced images). CNAB may be useful to look at for this use case.

> Notice the skopeo command to ensure the image exists in the registry before adding the reference.

There's also `regctl image copy` if you don't want to manage multiple tools. 😄
