### ISSUE TITLE
[Question] Can I export local image to .tar file within podman?

### ISSUE THREAD

**Issue by TyeolRik** [regclient/regclient#638]
Thanks for providing good program!
among 3 packages, `crane`, `skopeo`, `regctl`, only your program works well on my system!

### Question

Can I export local image to .tar file? (I am currently using podman)

I want to preserve my Digests or RepoDigests (whatever at least one) for closed network system. I successed with below commands

```
# origin node
$ ./regctl image export <IMAGE_NAME>@sha256:<IMAGE_DIGEST> ./regctl.tar
$ scp ./regctl.tar <ANOTHER_NODE>

# another node
$ podman load -i regctl.tar
$ podman run -it <IMAGE_NAME>@sha256:<IMAGE_DIGEST> # SUCCESS!
```

But the thing is, above commands only works when online (internet connected). I am looking for export command if there is no internet connection. Is it possible?

### Version

```text
$ ./regctl version
VCSTag:     v0.5.6
VCSRef:     c848ed2ec4c23f88a7e1a96f75270ad416671eb3
VCSCommit:  c848ed2ec4c23f88a7e1a96f75270ad416671eb3
VCSState:   clean
VCSDate:    2023-12-24T14:14:41Z
Platform:   linux/amd64
GoVer:      go1.21.5
GoCompiler: gc

$ podman -v
podman version 4.6.1
```

### Environment

- Running as binary or container: binary
- Host platform: x86_64, CentOS 8 Stream, podman (v4.6.1)
- Registry description: nothing. only local in closed network with some tar files. (`podman save -o`)

**Comment by sudo-bmitch** [comment]
`regctl` can read/write from registries, an OCI layout, and an export to a tar file with either the OCI Layout or Docker archive format. So in this case, you would run a `podman save ...` to output to any of those formats (their [docs](https://docs.podman.io/en/stable/markdown/podman-save.1.html) describe the ability to output to multiple formats), and then either `podman load` to import that save on another machine, or a `regctl image import` or `regctl image copy ocidir://$path/to/dir $dest` to work with the Docker archive or OCI Layout.

Note that `regclient` doesn't talk directly to podman, docker, containerd, kubernetes, or any other container runtimes directly. The furthest it goes is the Docker archive tar file.

**Comment by sudo-bmitch** [comment]
Apologies, I misinterpreted your question. I thought you were asking if regctl can talk directly to podman (which it doesn't). From the errors shown, I believe the issue is that the image is not being tagged in podman. From https://github.com/containers/podman/issues/2210 I believe you can explicitly tag the image by running:

```shell
podman load -i ubi.tar registry.access.redhat.com/ubi9/ubi:9.3-1361.1699548029
```

There's also multiple digests here, which gets confusing. First, there's the index that holds the platform specific manifests. The index/manifest list has it's own digest that you were using:

```
$ regctl manifest get registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
Name:        registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
MediaType:   application/vnd.docker.distribution.manifest.list.v2+json
Digest:      sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
             
Manifests:   
             
  Name:      registry.access.redhat.com/ubi9/ubi@sha256:5dc85ec81a0d2cc5d19164f80b8d287b176483fd09a88426ca2f698bb2bd09de
  Digest:    sha256:5dc85ec81a0d2cc5d19164f80b8d287b176483fd09a88426ca2f698bb2bd09de
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      registry.access.redhat.com/ubi9/ubi@sha256:113204124d07727303e50b2e6b87a01784180c187043f842a1af92e4f389c0e5
  Digest:    sha256:113204124d07727303e50b2e6b87a01784180c187043f842a1af92e4f389c0e5
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
             
  Name:      registry.access.redhat.com/ubi9/ubi@sha256:15098e9778f5502d928d8b0e5df356e4ffa53cb8c9356d57e12b60873f4b47b7
  Digest:    sha256:15098e9778f5502d928d8b0e5df356e4ffa53cb8c9356d57e12b60873f4b47b7
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le
             
  Name:      registry.access.redhat.com/ubi9/ubi@sha256:8466c9efca1a9342ba174e9540cf939d0538adc46c2b93255567025a07a0f33b
  Digest:    sha256:8466c9efca1a9342ba174e9540cf939d0538adc46c2b93255567025a07a0f33b
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```

But when podman imports it, the config digest from the platform specific manifest is used to reference the image:

```
$ regctl manifest get registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359 --platform linux/amd64
Name:        registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
MediaType:   application/vnd.docker.distribution.manifest.v2+json
Digest:      sha256:5dc85ec81a0d2cc5d19164f80b8d287b176483fd09a88426ca2f698bb2bd09de
Total Size:  78.772MB
             
Config:      
  Digest:    sha256:2a2c2b7af8db0755dce3da01d17da4eef17841d6ebebdb201ecd5a88629457ce
  MediaType: application/vnd.docker.container.image.v1+json
  Size:      6409B
             
Layers:      
             
  Digest:    sha256:b824f4b30c465e487e640bdc22e46bafd6983e4e0eabf30085cacf945c261160
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      78.772MB
```

And the blob digest comes from the uncompressed blob, which can be seen in the rootfs section of the config:

```
$ regctl image config registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359 --platform linux/amd64
...
  "rootfs": {                                     
    "type": "layers",                                                                                                                                                                                              
    "diff_ids": [        
      "sha256:584953c6b22faba1a93fb106297d108abefed3b1866099baa8cc6b0ab92bc47a"
    ]
  }, 
...
```

I believe podman is working similar to docker here, where only a single platform image is imported. When a single platform manifest is exported in regctl, both the OCI layout and docker archive format are included in the same tar, which may give podman the metadata it needs to automatically tag the image, e.g.:

```shell
regctl image export --platform linux/amd64 <IMAGE_NAME>@sha256:<IMAGE_DIGEST> ./regctl.tar
...
podman load -i regctl.tar 
```

Exporting a single platform, if you don't need the multi-platform manifest, can save you a lot of download time and disk space. But realize the digest will be the platform specific digest and not the manifest list digest.

Without testing, I can't say if podman would use the image name from the docker archive, or if it prefers the OCI Layout since both are included that regctl export. If none of the above help, podman may include additional metadata it their own export that regclient can include. To see what they are creating, try the following:

```
# this should output the image in the ubi directory if I'm reading their documentation correctly
podman save --format oci-dir -o ubi registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
jq . <ubi/index.json
```

I'd be interested in seeing if they include any annotations in there pointing to `registry.access.redhat.com/ubi9`. If so, that's something I can easily add to regclient.

**Comment by TyeolRik** [comment]
Thanks for your kind reply.

However, I tried as you said,

```bash
[host1]$ podman save --format oci-dir -o ubi registry.access.redhat.com/ubi9/ubi@sha256:6b95efc134c2af3d45472c0a2f88e6085433df058cc210abb2bb061ac4d74359
[host1]$ scp -r ubi host2:/root/

[host2]$ podman load -i /root/ubi
[host2]$ podman image inspect localhost/ubi:latest
[
     {
          "Id": "2a2c2b7af8db0755dce3da01d17da4eef17841d6ebebdb201ecd5a88629457ce",
          "Digest": "sha256:19cf2549663ac9e7dead59a723dfd2e2ae9f861efbe65335623094a0d2373044",
          "RepoTags": [
               "localhost/ubi:latest"
          ],
```

Doesn't work as I wanted.. :( Image digest always changed..

Thanks for trying to help. I think I have to do something with opening [local registry](https://hub.docker.com/_/registry) for solving this problem :(
