### ISSUE TITLE
[Issue] Pinging registry slows down when registry is not available

### ISSUE THREAD

**Issue by bigtallcampbell** [regclient/regclient#643]
### Current Behavior

Pinging the registry before the registry is configured is slowing down operations due to sleeping backoff and wait.  Local registries / configuration may not be available at the first pass (certificate setup, authentication, proxies, etc.)

### Expected Behavior

No ping / configuration check, or allow it to be skipped / disabled

### Steps To Reproduce

1. Configure regctl like below `regctl registry set localhost:5000 --tls enabled --req-concurrent 15 --req-per-sec 15`
1. Sleep / backoff starts
1. Start a local registry: `docker run -dp 5000:5000 --restart=always --name registry registry`

Ideally something like:
regctl registry set localhost:5000 --tls enabled --req-concurrent 15 --req-per-sec 15 --skip-ping-check

### Version
[https://github.com/regclient/regclient/releases/tag/v0.5.6](v0.5.6)

**Comment by sudo-bmitch** [comment]
Thanks for the suggestion. It took a second to add the tests, but otherwise this was an easy addition. This will be available with the `edge` images shortly, and CI outputs binaries if you don't want to build them yourself to test: https://github.com/regclient/regclient/actions/runs/7576064944.

If it gives you any trouble, let me know and we can reopen.
