### ISSUE TITLE
[Issue] Missing Output when using --format '{{jsonPretty .}}'

### ISSUE THREAD

**Issue by luckylinux** [regclient/regclient#757]
### Current Behavior
I am trying to compare the **Image** (specific to a given Platform) between what is on Docker Hub / docker.io and what I have on my Local Registry Mirror.

I am seeing a weird inconsistency between the JSON Output and the "Normal" / Default Output.

### Expected Behavior
The two Output Formats should return the same Values, just in a Different Format.

As it is right now, the Most Important Information (besides the Manifest Digest which can be checked using `regctl manifest head`) and which can be compared on Docker Hub Website is missing (as mentioned above):
![image](https://github.com/regclient/regclient/assets/7126291/712bc589-9cba-4018-8138-bf387b04e73f)

### Steps To Reproduce
JSON Output:
```
root@80c71a2c3a98:/opt/app# regctl image manifest --host docker.io "alpine:latest" --platform linux/amd64 --format '{{jsonPretty .}}'  | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1472,
    "digest": "sha256:1d34ffeaf190be23d3de5a8de0a436676b758f48f835c3a2d4768b798c15a7f1"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 3622094,
      "digest": "sha256:d25f557d7f31bf7acfac935859b5153da41d13c41f2b468d16f729a5b883634f"
    }
  ]
}
```

"Normal" / Default Output:
```
root@80c71a2c3a98:/opt/app# regctl image manifest --host docker.io "alpine:latest" --platform linux/amd64
Name:        alpine:latest
MediaType:   application/vnd.docker.distribution.manifest.v2+json
Digest:      sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
Total Size:  3.622MB
             
Config:      
  Digest:    sha256:1d34ffeaf190be23d3de5a8de0a436676b758f48f835c3a2d4768b798c15a7f1
  MediaType: application/vnd.docker.container.image.v1+json
  Size:      1472B
             
Layers:      
             
  Digest:    sha256:d25f557d7f31bf7acfac935859b5153da41d13c41f2b468d16f729a5b883634f
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      3.622MB

```

As can be seen, the first Elements are ignored when outputting in JSON Format.
Missing are:

- Name:        alpine:latest
- Digest:      sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
- Total Size:  3.622MB

And for some Reason the JSON has one EXTRA field:
- "schemaVersion": 2,

### Version

```
VCSTag:     v0.6.1
VCSRef:     766ee6291f882778207ff42207f9ca8b1da54e57
VCSCommit:  766ee6291f882778207ff42207f9ca8b1da54e57
VCSState:   clean
VCSDate:    2024-05-14T13:18:19Z
Platform:   linux/amd64
GoVer:      go1.22.3
GoCompiler: gc
```

(using the official AMD64 Binaries provided by you on https://github.com/regclient/regclient/ running inside a custom Docker/Podman Container based on Debian Testing - https://github.com/luckylinux/container-registry-tools and https://github.com/luckylinux/docker-sync-registries)

For what it's worth, I also tested (on my Desktop, i.e. running on "Baremetal" Ubuntu 24.04 AMD64), an older Release built from Source (IIRC it was built on Ubuntu 23.10 AMD64 though), but that yields the same Issue:
```
VCSTag:     (devel)
VCSRef:     aeb6854d17bb72e3e3e6522484d81d36057f30a8
VCSCommit:  aeb6854d17bb72e3e3e6522484d81d36057f30a8
VCSState:   clean
VCSDate:    2024-03-31T19:51:05Z
Platform:   linux/amd64
GoVer:      go1.21.1
GoCompiler: gc

```

### Environment

- Running as binary or container: running your Official AMD64 Binary into my own Container (https://github.com/luckylinux/container-registry-tools and https://github.com/luckylinux/docker-sync-registries)
- Host platform: AMD64 (KVM Virtual Machine)
- Registry description: Unsure

### Anything else

In `headers` Format I am getting this:
```
root@80c71a2c3a98:/opt/app# regctl image manifest --host docker.io "alpine:latest" --platform linux/amd64 --format headers                  
Content-Length: 528
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Date: Sun, 02 Jun 2024 09:58:49 GMT
Docker-Content-Digest: sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
Docker-Distribution-Api-Version: registry/2.0
Docker-Ratelimit-Source: 78.31.254.43
Etag: "sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b"
Ratelimit-Limit: 100;w=21600
Ratelimit-Remaining: 94;w=21600
Strict-Transport-Security: max-age=31536000
```

I could do a quick Fix / Hack on my side and try to parse either of these, but I guess the proper Solution would be to get this fixed ...

Headers:
```
regctl image manifest --host docker.io "alpine:latest" --platform linux/amd64 --format headers | grep -i "Docker-Content-Digest" | sed -E "s|^Docker-Content-Digest:\s*?([0-9a-zA-Z\:]+?)$|\1|"
sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
```

"Normal" / Default:
```
regctl image manifest --host docker.io "alpine:latest" --platform linux/amd64 | grep -Ei "^Digest:" | head -1  | sed -E "s|^Digest:\s*?([0-9a-zA-Z\:]+?)$|\1|"
sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
```

Or did I forget to use some custom Option when running the Command ?

As discussed/briefed the previous time I opened an issue on your Project Issue Tracker, I am trying to either compare the Manifest using `head` (in case I have a lot of Disk Space available, I will just mirror ALL Architectures) or comparing the platform-specific `digest` between the Docker Registry and my Local Registry Mirror (in case Disk Space is more scarce).

**Comment by sudo-bmitch** [comment]
The manifest output in `jsonPretty` is the original manifest, parsed into the known fields, and with whitespace to make it readable. You can see the specs for those manifests at:

- https://github.com/distribution/distribution/blob/v2.8.3/docs/spec/manifest-v2-2.md
- https://github.com/opencontainers/image-spec/blob/main/image-index.md
- https://github.com/opencontainers/image-spec/blob/main/manifest.md

The `printPretty` output is specially formatted for human consumption, and it pulls in metadata like the digest, the name of the pulled image, and a sum of the bytes for each of the layers. Those pretty printers can be seen in the manifest package, e.g. https://github.com/regclient/regclient/blob/v0.6.1/types/manifest/oci1.go#L215-L271

It's not possible to include the digest of the manifest inside of the manifest, since that would be a hash of itself and require circular hash (a hash of content that contains the value of the output hash in the input).

If your goal is to know the size of each of the layers in the manifest, you'd need to pull the manifest to see each of the layer descriptors and sum up the size values. That cannot be done with a head request.

If you want to know the digest of a manifest, you can see that with `regctl image digest` or `regctl manifest head --require-digest`. It will attempt to use a HEAD request, but on registries that do not include the digest in the headers, it will fall back to a GET request and hash the content.

You can also get more complicated with [Go templates](https://pkg.go.dev/text/template) to call multiple methods like listing the layers and getting the reference directly from the shell: https://pkg.go.dev/github.com/regclient/regclient@v0.6.1/types/manifest#Manifest. E.g.:

```shell
regctl manifest get ghcr.io/regclient/regctl --format 'Digest: {{.GetDescriptor.Digest}}{{print "\nJSON:\n"}}{{jsonPretty .}}'
```

If all you want to do is avoid copying all of the platforms, I'd recommend having a look at https://github.com/distribution/distribution/pull/3536. `regctl image copy` has an experimental/hidden `--platforms` (plural) flag that accepts a list of platforms to include. And regsync has a similar `platforms` field, also experimental. These have not be tested, and in use can result in errors if either the registry does not support sparse manifests (which is almost all of them, hence the feature being experimental and untested). It would also result in errors from clients if they attempt to pull a platform that does not exist on the registry, often a returning confusing 404 when pulling a tag (that is a manfiest list or index) that does exist.

**Comment by luckylinux** [comment]
Thank you for your quick Reply.

Isn't it just this the Command I was looking for ?

```
regctl manifest get docker.io/library/alpine:latest --format '{{.GetDescriptor.Digest}}' --platform linux/amd64
sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
```

**Comment by sudo-bmitch** [comment]
If you just want the digest, then `regctl image digest` or `regctl manifest head --require-digest` are the commands you want.

**Comment by luckylinux** [comment]
Indeed this also works :+1: 
```
regctl image digest docker.io/library/alpine:latest --platform linux/amd64
sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
```

Whether this does a GET or a HEAD request is not clear to me. Based on what we discussed last time, I recall this will perform a GET requests, since it's invoked with `--platform XXX`:
```
regctl manifest head --require-digest docker.io/library/alpine:latest --platform linux/amd64
sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b
```

**Comment by sudo-bmitch** [comment]
To resolve a platform, it has to pull the manifest list or index, which is why you typically don't want that flag in automation. You can run with `-v debug` to see the GET and HEAD requests.
