### ISSUE TITLE
[Feature] Add option for a default registry

### ISSUE THREAD

**Issue by jamielinux** [regclient/regclient#790]
### Current Behavior

Unless I'm missing something, currently for every query (eg, `regctl repo ls`, `regctl tag ls` etc) you have to specify the registry. If all of your images are in a single private registry, typing out the registry seems a little redundant and it'd be nice if you could set a default that is used if not specified on the command-line.

### Expected Behavior

Be able to run `regctl repo ls` without specifying the registry and `regctl` will use the default registry if one is set.

Be able to run `regctl tag ls my_image` without specifying the registry and `regctl` will use the default registry if one is set.

etc.

### Version

```text
VCSTag:     v0.6.1
VCSRef:     766ee6291f882778207ff42207f9ca8b1da54e57
VCSCommit:  766ee6291f882778207ff42207f9ca8b1da54e57
VCSState:   clean
VCSDate:    2024-05-14T13:18:19Z
Platform:   linux/amd64
GoVer:      go1.22.3
GoCompiler: gc
```

**Comment by sudo-bmitch** [comment]
Creating multiple versions of the default registry would result in [dependency confusion attacks](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) that image references have avoided by requiring a registry name rather than overlapping global namespaces (and that registry name is assumed to be `docker.io` when not provided, avoiding any ambiguity). RedHat implemented this feature on their tools, but then told users [to avoid using the feature](https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name). Docker has also [refused similar requests](https://github.com/moby/moby/issues/33069).

Because of these security concerns, I'm not willing to implement this. I realize that some might use a feature like this responsibly. But I don't have the bandwidth to deal with any resulting CVEs this could create for other users.

**Comment by jamielinux** [comment]
That's fair, and thanks for your reply and explanation @sudo-bmitch :)
