### ISSUE TITLE
[Issue] regsync to full registry using jfrog artifactory as a source not working

### ISSUE THREAD

**Issue by lia39** [regclient/regclient#792]
### Current Behavior

In artifactory, to access the repositories list there is a sub path to the url: artifactory.url.com:443/api/docker/my-docker-repo/v2/_catalog or just v2/<docker-repo>/_catalog 

Is there a way to add the prefix to the source in the regsync.yml?

https://jfrog.com/help/r/artifactory-what-is-the-jfrog-repository-catalog-file-in-local-docker-repositories/artifactory-what-is-the-jfrog/repository.catalog-file-in-local-docker-repositories

https://jfrog.com/help/r/jfrog-rest-apis/list-docker-repositories

**Comment by sudo-bmitch** [comment]
That looks like the reverse proxy step was skipped, or you're trying to talk to the artifactory API and not the OCI/Docker API.

https://jfrog.com/help/r/jfrog-artifactory-documentation/the-repository-path-method-for-docker?section=UUID-85fb83b5-d96d-e41f-04d3-ce5788180d31_N1708516923407

**Comment by lia39** [comment]
Yes, sorry I didnt specify, I can't use a reverse proxy in my network, I need to work with a different URI, is it something that might be a possibility in the future or not? 
thanks for the help!

**Comment by sudo-bmitch** [comment]
Nope, you need to talk to the OCI API for regclient, and those all start with `/v2` at the root. regclient doesn't implement individual registry APIs.

**Comment by ennekein** [comment]
Hi @sudo-bmitch, moving the discussion here from #820.

We are using Artifactory containing multiple Docker registries set up with the Repository Path method (https://jfrog.com/help/r/jfrog-artifactory-documentation/the-repository-path-method-for-docker).

Our registry APIs are exposed with the following URL format: `https://<hostname>/v2/<registry name>/<...>`. This allows to access multiple Docker and OCI registries within the same Artifactory URL, which is very useful to pull images from various team-owned registries.

We are trying to use the regclient go module to run commands against an OCI registry in Artifactory/JFrog. We are hitting an issue at the `RepoList` function, because it formats the API call as `https://<hostname>/v2/_catalog`. I see that the `repository` parameter in your API struct could be used to add the registry name between `/v2` and the command path, but it is not exposed by the `RepoList` function.

Are Artifactory Docker/OCI registries exposed with the Repository Path method something you would want to support?

Since this is a leftover from the legacy Docker registry API, not regulated by the Distribution spec, and that the implementation is subjective to the registry implementation, I don't see why an optional `<name>` couldn't be allowed like `https://<hostname>/v2/[<name>/]_catalog`. Please tell me if you disagree.

**Comment by sudo-bmitch** [comment]
@ennekein My mistake. When I first read #820 I interpreted it as asking to support the Artifact APIs (without the /v2 at the top). 

> I don't see why an optional `<name>` couldn't be allowed like `https://<hostname>/v2/[<name>/]_catalog`.

That's not technically part of the `_catalog` API which comes from the Docker implementation. Details of that API are currently documented by the distribution/distribution project: https://distribution.github.io/distribution/spec/api/#listing-repositories

Effectively, the path method in Artifactory is breaking this API if they are implementing it at an unsupported location. The ports method is more likely to be standards compliant (I haven't tested this), though I understand that it requires more work per mirror to maintain.

The better solution to this is for OCI to define a repository listing API that isn't only scoped to the top level, but that's not going to happen for a while (specs change very slowly). In the nearer term, some progress may be made to change how mirrors are supported with an added parameter on API requests, rather than a repository. That would move the `_catalog` API back up to the top level without needing a separate host or repository path.

For now, I'm going to decline this since it would be an Artifactory specific change. Seeing other registries implement the API within a repository would make this worth reconsidering.

**Comment by ennekein** [comment]
Alright, that makes sense. Thank you for the long answer.
