### ISSUE TITLE
[Feature] Provide support for defining default settings for hosts inside regctl's config

### ISSUE THREAD

**Issue by gsharma85** [regclient/regclient#802]
### Current Behavior
When a login to registry command is executed, regctl creates a config.json in user's home directory and saves registry host related config there. Users can themselves also add hosts inside this config and can provide settings like credhelper, reqPerSec, requestConcurrent etc. When we have a huge number of registries these settings are pretty much similar across hosts and we end up having a very big config with repeated information.

Another challenge is that you need to precompile a list of registries that you want to apply custom config like credhelper, reqPerSec, requestConcurrent before actual regctl command is executed. This is mainly problematic when you are pushing regctl to many different linux boxes where applications/developers can make use of it.

### Expected Behavior

Provide a way to set common settings between hosts in a separate element say default under hosts element in config json. Now when a login to registry command is executed, regctl should create a host entry inside hosts element in config.json by using the default values from default element instead.

### Example Solution

hosts: {
  default: {
      credhelper: "path to cred helper binary"
      reqPerSec: 
      reqConcurrent: 
      tls: "enabled"
  },
  mytestacr.azurecr.io: {
   
  },
  docker-hub1.io: {
  
  }
}

### Version

0.7.1

### Environment

- Running as a binary
- Host platform: Linux and Windows
- Registry: ACR and Harbor

**Comment by sudo-bmitch** [comment]
There are currently some top level fields, which can be added to: https://github.com/regclient/regclient/blob/08a0ce7d981230fa413169ec03386db1de4fb447/cmd/regctl/config.go#L28-L35

My approach would be to add a new field, and use the value as a default that get merged to all host entries as they are loaded. Then `regctl config set` could be extended to change the values of those fields. Ideally `regctl config set` should also able to remove a default value so that manually editing the config.json isn't needed to undo an action.

Note that I'm working on some network refactoring, so `reqPerSec` and `reqConcurrent` should probably be avoided for now (if they are still there, the need for them should be lower in the future). And TLS should never default to anything other than "enabled" though some kind of auto-detect setting for localhost may be useful.

**Comment by sudo-bmitch** [comment]
I believe #821 resolves your use case, but if there are more options or flags needed, let me know and we can reopen this.
