### ISSUE TITLE
[Feature] Proxy support

### ISSUE THREAD

**Issue by marcellourbani** [regclient/regclient#833]
### Current Behavior

Proxy settings in ~/.docker/config.json are ignored

### Expected Behavior

I would expect that if a proxy is configured it will be used

### Example Solution

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "somesecret"
		}
	},
	"proxies": {
		"default": {
			"httpProxy": "http://myproxy.local:80"
		}
	}
}
```
I would expect requests to go through the proxy, but they don't
### Version

```text
VCSTag:     (devel)
VCSRef:     7193ea7eb9172a8ca8320e139d739d0e87afb3ef
VCSCommit:  7193ea7eb9172a8ca8320e139d739d0e87afb3ef
VCSState:   clean
VCSDate:    2024-08-03T20:22:30Z
Platform:   linux/amd64
GoVer:      go1.23.1
GoCompiler: gc
```

### Environment

Artchlinux x86 _64, up to date
binary from AUR package aur/regclient-regctl 0.7.1-2 (1 | 0.21) 
various registries, docker Hub and my private one

### Anything else

will be the same for any registry

**Comment by marcellourbani** [comment]
It's something I need, and I'm having a go at doing myself
Doesn't seem too challenging, except:

- supporting every possible combination of generic and host specific rules could be challenging, guess will need a bunch of tests
- as I understand the go http library (not much) I'm supposed to specify the proxy in the transport when I create an http.Client, and here I only have one for many hosts who might have different proxy settings. I can deal with that, but might need some refactoring

Let me know if you have any thoughts, and thanks for creating this tool

**Comment by sudo-bmitch** [comment]
To verify, does this mean you have multiple http proxies on your network, and accessing different registries requires going through different proxies? 

I want to exclude the more common scenarios, where many have a single http proxy, but that proxy is only used for traffic going out of the network. And it also excludes environments that setup multiple registry proxies, instead of a generic http proxy.

**Comment by marcellourbani** [comment]
I don't, but the configuration file does allow that. Will do my best and send a PR

**Comment by sudo-bmitch** [comment]
In that case, I'd consider this the same as #628, which is asking for a feature that isn't really needed in any real world use case. I'd be very hesitant accepting any feature that alters the transport for proxy settings since that could repeat #614 and I don't have a good test environment to prevent a regression. The `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` variables should just work, and be supported by lots of tools, including docker.

In fact, looking at the docker documentation, those configuration settings are just another way to set the environment variables: https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client

**Comment by sudo-bmitch** [comment]
I believe this would be an invalid change since the `~/.docker/config.json` is not used for registry communication:

```shell
$ docker network create proxy-test
cae860455e4055531ea111c1d8c715bfd5bbf85f7ccbd5cf74bffc340a89ee6d

$ # inspect proxy-test to get the subnet
$ docker network inspect proxy-test
[
    {
        "Name": "proxy-test",
        "Id": "cae860455e4055531ea111c1d8c715bfd5bbf85f7ccbd5cf74bffc340a89ee6d",
        "Created": "2024-10-08T16:34:32.820166518-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.65.0/24",
                    "Gateway": "192.168.65.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

$ # run a DinD server on the network with the HTTPS_PROXY value set to x.x.x.10:3129
$ docker run -d --rm --privileged --net proxy-test --network-alias docker \
  -v "dind-proxy:/var/lib/docker" -v "dind-proxy-ccerts:/certs/client" -e DOCKER_TLS_CERTDIR=/certs \
  -e HTTPS_PROXY=http://192.168.65.10:3129 --name "dind-proxy" docker:stable-dind
fbd3365762eb446a4436b42c90ec43bdd3d31729eba168d05ea48e2dea7e4e36

$ # run the client with the HTTPS_PROXY value set to x.x.x.12:3129
$ docker run -it --rm --privileged --net proxy-test \
  -v "dind-proxy-ccerts:/certs/client:ro" -e DOCKER_TLS_CERTDIR=/certs \
  -e "HTTPS_PROXY=https://192.168.65.12:3129:3129" -e "NO_PROXY=192.168.0.0/16,docker" \
  -e DOCKER_HOST=tcp://docker:2376 docker:stable sh

/ # mkdir ~/.docker
/ # # configure the config.json with the HTTPS_PROXY value set to x.x.x.11:3129
/ # cat >~/.docker/config.json <<EOF
{
 "proxies": {
   "default": {
     "httpsProxy": "https://192.168.65.11:3129"
   }
 }
}
EOF

/ # # note the proxy IP that shows up here is from the server (x.x.x.10), not the client or config.json IPs
/ # docker pull busybox
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 192.168.65.10:3129: connect: no route to host
/ # exit

$ docker stop dind-proxy
$ docker network rm proxy-test
```

The docs describe the `config.json` setting as only being used to set the environment variables in containers run by docker, which means there is no need for regclient to support it.
