### ISSUE TITLE
[Issue] Not copied platforms still listed when using experimental --platforms filtering

### ISSUE THREAD

**Issue by jeremy-clerc** [regclient/regclient#836]
### Current Behavior

When using the hidden and experimental flag `--platforms`, the pushed manifest contains in the manifest list a reference for all platforms even the ones that have not been copied.

```
{
  ...
  manifests: [
    .. linux/amd64 ..
    .. windows/amd64 ..
   ]
}
```

The current registry I have tested on, Sonatype Nexus, is not happy with that because if I filter for linux/amd64 for example, the copy will fail, because it will say that it does not find in its storage the reference for the windows/amd64 one.

### Expected Behavior

The pushed multi platform manifest only contains the platforms that were filtered, from the previous example only a ref to linux/amd64

### Steps To Reproduce

Take a multi platform image like golang:1 and try to copy it by filtering the platform.

`regctl image copy --platforms linux/arm64 --platforms linux/amd64 golang:1 some-nexus-repo/golang:1`

### Version

```text
VCSTag:     (devel)
VCSRef:     87ac18eeef0912e6fa675324e10ee9b438a1759d-dirty
VCSCommit:  87ac18eeef0912e6fa675324e10ee9b438a1759d
VCSState:   dirty
VCSDate:    2024-10-07T16:28:49Z
Platform:   darwin/arm64
GoVer:      go1.22.5
GoCompiler: gc
```

### Environment

- Running as binary or container: binary latest released version / built from source
- Host platform: darwin/arm64
- Registry description: Sonatype Nexus https://help.sonatype.com/en/docker-registry.html

### Anything else

Awesome tool you've made, thank you!

Before I open a PR, my approach is the following https://github.com/jeremy-clerc/regclient/commit/189a4a753b2f0c72e01df7dc3bff737cbd529d3d

I think that even if a registry is less restrictive it gives false information if the copied manifest lists platforms that have not actually been copied.

Thank you

**Comment by sudo-bmitch** [comment]
The feature is intentionally marked as experimental because there aren't many registries that support the concept of a sparse manifest. It's designed for environments where they want an exact copy of the of the original image, with a matching digest, for security reasons (perhaps the index was signed or includes build attestations) but they do not need the other platforms locally.

To copy a single platform, you can use the `regctl image copy --platform` option. This will select the desired platform specific manifest and only copy that.

To create a new index (or manifest list) with multiple platforms from another image, use `regctl index create`, e.g.:

```shell
regctl index create registry.example.org/alpine:latest \
  --ref alpine:latest --platform linux/amd64 --platform linux/arm64
```

This new index will not have a matching digest from the original index, but the individual platform specific manifests will match the source.

**Comment by sudo-bmitch** [comment]
More details on the sparse manifest requirements can be found in the OCI mailing list discussion: https://groups.google.com/a/opencontainers.org/g/dev/c/Uw8xdBOr444

**Comment by jeremy-clerc** [comment]
Totally makes sense, and Sparse Index did not come to mind at all, I should have dig more, sorry about that,  thanks a lot for your detailed and quick reply.
