### ISSUE TITLE
[Issue] registry copy changes the target port of the instance

### ISSUE THREAD

**Issue by mobidyc** [regclient/regclient#888]
### Current Behavior

I try to migrate one local registry to another local one.
But the process tries to access the non existant myregistry:**5000** registry instance.

### Expected Behavior

copy the src to the destination

### Steps To Reproduce

```shell
./regctl image copy myregistry:5001/back:v7.5 127.0.0.1:5002/back:v7.5
time=2024-12-27T20:39:01.683Z level=WARN msg="Changing hostname settings for registry" orig=myregistry:5000 new=127.0.0.1:5000 host=myregistry:5000
time=2024-12-27T20:39:01.683Z level=WARN msg="Changing TLS settings for registry" orig=enabled new=disabled host=127.0.0.1:5002
time=2024-12-27T20:39:01.683Z level=WARN msg="Changing hostname settings for registry" orig=127.0.0.1:5002 new=127.0.0.1:5000 host=127.0.0.1:5002
Manifests: 0/0 | Blobs: 0.000B copied, 0.000B skipped | Elapsed: 3s
failed to access target registry: failed to request manifest head 127.0.0.1:5002/back:v7.5: Head "http://127.0.0.1:5000/v2/back/manifests/v7.5": dial tcp 127.0.0.1:5000: connect: connection refused
```

### Version

```shell
./regctl version
VCSTag:     v0.8.0
VCSRef:     106f460aad78a8c017b35c3d716435074920307f
VCSCommit:  106f460aad78a8c017b35c3d716435074920307f
VCSState:   clean
VCSDate:    2024-12-10T20:56:08Z
Platform:   linux/amd64
GoVer:      go1.23.4
GoCompiler: gc
```

### Environment

- Running as binary or container: downloaded binary
- Host platform: platform linux x86
- Registry description: both registries are docker container registry:2 and run locally

**Comment by sudo-bmitch** [comment]
The warnings are just letting you know that settings are changing in unexpected ways between the docker and regctl configuration (since regctl loads the docker configs first). You can see the configuration settings in `$HOME/.regctl/config.json` or in the output of `regctl config get`.

In that configuration, I think you'll see that you've overridden the hostname for a couple of registry names, which should not be needed in your use cases. It's probably easiest to delete that config and start clean, but the following would also fix your specific issue:

```shell
regctl registry set 127.0.0.1:5002 --hostname 127.0.0.1:5002
regctl registry set myregistry:5000 --hostname myregistry:5000
```

**Comment by mobidyc** [comment]
I see, I probably edited the config file and mixed the hosts/names, my bad.
thank you for pointing out this, it works pretty well with the correct configuration.
